services:
  ruby-datascience-notebook:
    build:
      context: .
      dockerfile: "Dockerfile"
    ports:
      - "8888:8888"
    volumes:
      - "./:/home/jovyan/work:rw"
  python-datascience-notebook:
    image: jupyter/datascience-notebook:python-3.11
    ports:
      - "8889:8889"
    environment:
      - JUPYTER_PORT=8889
    volumes:
      - ./:/home/jovyan/work:rw
    command: start-notebook.py --ServerApp.root_dir=/home/jovyan/work
